framework:
    messenger:
        default_bus: messenger.bus.default
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
        transports:
            process_transaction:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 2
                options:
                    exchange:
                        name: 'x.prc_trans'
                        type: 'topic'
                    queues:
                        q.gen_ntf: &quorum-queue-args
                            arguments:
                                x-queue-type: quorum
                    delay:
                        exchange_name: 'x.delays-internal'
        routing:
            App\Application\Infrastructure\Message\ProcessTransactionMessage: process_transaction
            App\Application\Infrastructure\Message\TransferCommissionFeeFoundsMessage: process_transaction

when@test:
    framework:
        messenger:
            transports:
                process_transaction: test://
