services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Adapter/Secondary/Entity/'
            - '../src/Kernel.php'

    App\Adapter\Secondary\Purger\TestPurgerFactory:
        tags:
            - { name: 'doctrine.fixtures.purger_factory', alias: 'test_purger' }

when@test:
    services:
        App\Tests\Support\Override\DatabaseManager:
            decorates: App\Adapter\Secondary\DatabaseManager
            arguments: ['@.inner']

        App\Tests\Support\Override\MessageBus:
            decorates: App\Adapter\Secondary\MessageQueue\MessageBus
            arguments: ['@.inner']
