services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Adapter/Secondary/Entity/'
            - '../src/Kernel.php'

    App\Purger\TestPurgerFactory:
        tags:
            - { name: 'doctrine.fixtures.purger_factory', alias: 'test_purger' }

    ###> Transaction Chain Configuration ###
    App\Application\Infrastructure\COR\TransferChain\BankToBankTransaction:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\FinishChain'

    App\Application\Infrastructure\COR\TransferChain\InternalTransfer:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\FinishChain'

    App\Application\Infrastructure\COR\TransferChain\DeterminateTransferType:
        arguments:
            $internalTransfer: '@App\Application\Infrastructure\COR\TransferChain\InternalTransfer'
            $bankToBankTransaction: '@App\Application\Infrastructure\COR\TransferChain\BankToBankTransaction'

    App\Application\Infrastructure\COR\TransferChain\RaiseAndValidateTransferAmount:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\DeterminateTransferType'

    App\Application\Infrastructure\COR\TransferChain\ClientDailyTransferLimitValidation:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\RaiseAndValidateTransferAmount'

    App\Application\Infrastructure\COR\TransferChain\ClientOwnsSenderBankAccount:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\ClientDailyTransferLimitValidation'

    App\Application\Infrastructure\COR\TransferChain\TransferChainRootLink:
        arguments:
            $next: '@App\Application\Infrastructure\COR\TransferChain\ClientOwnsSenderBankAccount'

    App\Application\Port\Secondary\TransactionChainLinkInterface:
        alias: App\Application\Infrastructure\COR\TransferChain\TransferChainRootLink
    ###< Transaction Chain Configuration ###
